// --- Database Code Generator --------------------------------------------------
// Generates types.ts and migrations/index.ts from schema definitions

import { basename, extname } from "node:path";

import type { TableDefinition, ColumnDefinition } from "../types.js";

/** Map column data type to TypeScript type */
function columnToTsType(col: ColumnDefinition): string {
	switch (col.dataType) {
		case "serial":
		case "integer":
		case "bigint":
			return "number";
		case "boolean":
			return "boolean";
		case "timestamp":
		case "date":
		case "time":
			return "Date";
		case "json":
		case "jsonb":
			return "unknown";
		case "blob":
			return "Buffer";
		default:
			return "string";
	}
}

/** Generate TypeScript interface for a table */
function generateTableInterface(name: string, table: TableDefinition): string {
	const lines: string[] = [];
	lines.push(`\t${name}: {`);

	for (const [, col] of Object.entries(table.columns)) {
		let type = columnToTsType(col);

		// Wrap in Generated for serial/primaryKey columns
		if (col.dataType === "serial" || col.primaryKey) {
			type = `Generated<${type}>`;
		}

		// Add null for nullable columns
		if (col.nullable) {
			type += " | null";
		}

		// Add undefined for columns with defaults
		if (col.default && !col.primaryKey && col.dataType !== "serial") {
			type += " | undefined";
		}

		lines.push(`\t\t${col.name}: ${type};`);
	}

	lines.push(`\t}`);
	return lines.join("\n");
}

/** Generate types.ts content from table definitions */
export function generateTypesCode(tables: Record<string, TableDefinition>): string {
	const lines: string[] = [
		"// Auto-generated by @spacefn/db",
		"// Do not edit manually",
		"",
		'import type { ColumnType, Generated } from "kysely";',
		"",
		"export interface Database {",
	];

	for (const [key, table] of Object.entries(tables)) {
		lines.push(generateTableInterface(key, table));
	}

	lines.push("}");
	lines.push("");

	return lines.join("\n");
}

// --- Migration Index Generator ------------------------------------------------

/** Extract migration name from file path (e.g., "001_create_users" from "/path/to/001_create_users.ts") */
function migrationName(filePath: string): string {
	const file = basename(filePath);
	return file.replace(extname(file), "");
}

/** Generate migrations/index.ts content from individual migration files */
export function generateMigrationIndex(migrationFiles: string[]): string {
	// Filter out index files, sort by name for deterministic order
	const sorted = migrationFiles
		.filter((f) => !f.endsWith("/index.ts") && !f.endsWith("/index.js"))
		.sort((a, b) => migrationName(a).localeCompare(migrationName(b)));

	if (sorted.length === 0) return "";

	const lines: string[] = [
		"// Auto-generated by @spacefn/db",
		"// Do not edit manually",
		"",
		'import type { MigrationDefinition } from "@spacefn/db";',
		"",
	];

	// Import each migration
	for (let i = 0; i < sorted.length; i++) {
		const name = migrationName(sorted[i]);
		lines.push(
			`import { migration as migration${String(i).padStart(3, "0")} } from "./${name}.js";`,
		);
	}

	lines.push("");
	lines.push("export const migrations: MigrationDefinition[] = [");

	for (let i = 0; i < sorted.length; i++) {
		lines.push(`\tmigration${String(i).padStart(3, "0")},`);
	}

	lines.push("];");
	lines.push("");

	return lines.join("\n");
}
