// --- Database Code Generator --------------------------------------------------
// Generates types.ts from schema definitions

import type { TableDefinition, ColumnDefinition } from "../types.js";

/** Map column data type to TypeScript type */
function columnToTsType(col: ColumnDefinition): string {
	switch (col.dataType) {
		case "serial":
		case "integer":
		case "bigint":
			return "number";
		case "boolean":
			return "boolean";
		case "timestamp":
		case "date":
		case "time":
			return "Date";
		case "json":
		case "jsonb":
			return "unknown";
		case "blob":
			return "Buffer";
		default:
			return "string";
	}
}

/** Generate TypeScript interface for a table */
function generateTableInterface(name: string, table: TableDefinition): string {
	const lines: string[] = [];
	lines.push(`\t${name}: {`);

	for (const [, col] of Object.entries(table.columns)) {
		let type = columnToTsType(col);

		// Wrap in Generated for serial/primaryKey columns
		if (col.dataType === "serial" || col.primaryKey) {
			type = `Generated<${type}>`;
		}

		// Add null for nullable columns
		if (col.nullable) {
			type += " | null";
		}

		// Add undefined for columns with defaults
		if (col.default && !col.primaryKey && col.dataType !== "serial") {
			type += " | undefined";
		}

		lines.push(`\t\t${col.name}: ${type};`);
	}

	lines.push(`\t}`);
	return lines.join("\n");
}

/** Generate types.ts content from table definitions */
export function generateTypesCode(tables: Record<string, TableDefinition>): string {
	const lines: string[] = [
		"// Auto-generated by @spacefn/db",
		"// Do not edit manually",
		"",
		'import type { ColumnType, Generated } from "kysely";',
		"",
		"export interface Database {",
	];

	for (const [key, table] of Object.entries(tables)) {
		lines.push(generateTableInterface(key, table));
	}

	lines.push("}");
	lines.push("");

	return lines.join("\n");
}
