// --- Space Vite Plugin --------------------------------------------------------
// Convention-based route/middleware scanning
// Composes @spacefn/vite-plugin for code generation and Vite lifecycle

import { relative } from "node:path";

import { space as baseSpace } from "@spacefn/vite-plugin";
import type { Generator } from "@spacefn/vite-plugin";
import type { Plugin, ViteDevServer } from "vite";

import { scanRoutes, scanMiddlewares, scanPages } from "./generator.js";
import type { SpacePluginOptions, ScannedRoute, ScannedMiddleware, ScannedPage } from "./types.js";

// --- Code Generation ----------------------------------------------------------

function generatePagesCode(pages: ScannedPage[]): string {
	const lines: string[] = ["// Auto-generated by @spacefn/server", "// Do not edit manually", ""];
	lines.push('import { renderComponent } from "@spacefn/html";');

	// Import page/server modules
	for (let i = 0; i < pages.length; i++) {
		const p = pages[i];
		if (p.serverFile) {
			const rel = relative(process.cwd(), p.serverFile).replace(/\.ts$/, "");
			lines.push(`import * as Server_${i} from "#${rel}";`);
		}
		if (p.pageFile) {
			const rel = relative(process.cwd(), p.pageFile).replace(/\.ts$/, "");
			lines.push(`import Page_${i} from "#${rel}";`);
		}
	}

	lines.push("");
	lines.push("export const pages = [");
	for (let i = 0; i < pages.length; i++) {
		const p = pages[i];
		const hasServer = p.serverFile !== null;
		const hasPage = p.pageFile !== null;

		lines.push(`\t{`);
		lines.push(`\t\tpattern: "${p.pattern}",`);
		lines.push(`\t\tloader: ${hasServer ? `Server_${i}.loader` : "undefined"},`);
		lines.push(`\t\tactions: ${hasServer ? `Server_${i}.actions` : "undefined"},`);
		if (hasPage) {
			lines.push(`\t\tpage: (data) => renderComponent(Page_${i}(data)),`);
		} else {
			lines.push(`\t\tpage: undefined,`);
		}
		lines.push(`\t},`);
	}
	lines.push("];");
	lines.push("");

	return lines.join("\n");
}

function generateRoutesCode(routes: ScannedRoute[]): string {
	const lines: string[] = ["// Auto-generated by @spacefn/server", "// Do not edit manually", ""];

	for (let i = 0; i < routes.length; i++) {
		const r = routes[i];
		const rel = `#src/routes/${r.path}`;
		lines.push(`import * as Route_${i} from "${rel}";`);
	}

	lines.push("");
	lines.push("export const routes = [");
	for (let i = 0; i < routes.length; i++) {
		const r = routes[i];
		lines.push(`\t{`);
		lines.push(`\t\tpattern: "${r.pattern}",`);
		lines.push(`\t\tmethod: "${r.method}",`);
		lines.push(`\t\thandler: () => Promise.resolve(Route_${i}),`);
		lines.push(`\t},`);
	}
	lines.push("];");
	lines.push("");

	return lines.join("\n");
}

function generateMiddlewaresCode(middlewares: ScannedMiddleware[]): string {
	const lines: string[] = ["// Auto-generated by @spacefn/server", "// Do not edit manually", ""];

	for (let i = 0; i < middlewares.length; i++) {
		const mw = middlewares[i];
		const rel = `#src/middlewares/${mw.path}`;
		lines.push(`import * as Middleware_${i} from "${rel}";`);
	}

	lines.push("");
	lines.push("export const middlewares = [");
	for (let i = 0; i < middlewares.length; i++) {
		const mw = middlewares[i];
		lines.push(`\t{`);
		lines.push(`\t\tname: "${mw.name}",`);
		lines.push(`\t\thandler: Middleware_${i}.default,`);
		lines.push(`\t},`);
	}
	lines.push("];");
	lines.push("");

	return lines.join("\n");
}

// --- Pattern matching ---------------------------------------------------------

/** Match a URL pathname against a pattern like "/books/:slug" */
function matchPattern(pattern: string, pathname: string): boolean {
	const patternParts = pattern.split("/");
	const pathnameParts = pathname.split("/");

	if (patternParts.length !== pathnameParts.length) return false;

	for (let i = 0; i < patternParts.length; i++) {
		const pp = patternParts[i];
		// Dynamic segment matches anything
		if (pp.startsWith(":")) continue;
		// Catch-all matches anything
		if (pp.startsWith("*")) return true;
		// Exact match
		if (pp !== pathnameParts[i]) return false;
	}

	return true;
}

// --- Plugin Factory -----------------------------------------------------------

export function space(options: SpacePluginOptions = {}): Plugin[] {
	const root = options.root ?? process.cwd();

	// Create route generator: watch src/routes/ → generate .space/routes.ts
	const routeGenerator: Generator = {
		watch: "src/routes/**/*.ts",
		output: ".space/routes.ts",
		async generate() {
			const routes = await scanRoutes(root);
			if (routes.length === 0) return "";
			return generateRoutesCode(routes);
		},
	};

	// Create middleware generator: watch src/middlewares/ → generate .space/middlewares.ts
	const middlewareGenerator: Generator = {
		watch: "src/middlewares/**/*.ts",
		output: ".space/middlewares.ts",
		async generate() {
			const middlewares = await scanMiddlewares(root);
			if (middlewares.length === 0) return "";
			return generateMiddlewaresCode(middlewares);
		},
	};

	// Create pages generator: watch src/pages/ → generate .space/pages.ts
	const pagesGenerator: Generator = {
		watch: "src/pages/**/*.ts",
		output: ".space/pages.ts",
		async generate() {
			const pages = await scanPages(root);
			if (pages.length === 0) return "";
			return generatePagesCode(pages);
		},
	};

	// Resolve aliases for ssrLoadModule
	const aliasPlugin: Plugin = {
		name: "@spacefn/server:alias",
		config() {
			return {
				resolve: {
					alias: {
						"#space/": `${root}/.space/`,
						"#src/": `${root}/src/`,
					},
				},
			};
		},
	};

	// Dev server middleware: intercepts requests and serves pages/routes
	const devMiddleware: Plugin = {
		name: "@spacefn/server:dev",
		configureServer(server: ViteDevServer) {
			server.middlewares.use(async (req, res, next) => {
				try {
					const url = new URL(req.url ?? "/", `http://${req.headers.host ?? "localhost"}`);

					// Try pages first
					const pagesMod = await server.ssrLoadModule("#space/pages.ts");
					if (pagesMod?.pages) {
						for (const page of pagesMod.pages) {
							if (matchPattern(page.pattern, url.pathname)) {
								const data = page.loader ? await page.loader(new Request(url.toString(), { method: req.method })) : undefined;
								const html = page.page ? await page.page(data) : "";
								const body = String(html);
								res.setHeader("Content-Type", "text/html");
								res.end(body);
								return;
							}
						}
					}

					// Try routes
					const routesMod = await server.ssrLoadModule("#space/routes.ts");
					if (routesMod?.routes) {
						for (const route of routesMod.routes) {
							if (matchPattern(route.pattern, url.pathname) && (route.method === "*" || route.method === req.method)) {
								const mod = await route.handler();
								const handler = mod.default ?? mod;
								const response = await handler(new Request(url.toString(), { method: req.method, headers: req.headers as Record<string, string> }));
								if (response instanceof Response) {
									res.statusCode = response.status;
									for (const [key, value] of response.headers) {
										res.setHeader(key, value);
									}
									const body = await response.text();
									res.end(body);
									return;
								}
								res.end(String(response));
								return;
							}
						}
					}

					next();
				} catch (err) {
					next(err);
				}
			});
		},
	};

	// Delegate to @spacefn/vite-plugin for Vite lifecycle + file writing
	const generator = baseSpace({
		root,
		generators: [routeGenerator, middlewareGenerator, pagesGenerator],
	});

	return [generator, aliasPlugin, devMiddleware];
}

export type { SpacePluginOptions, ScannedRoute, ScannedMiddleware } from "./types.js";
