// --- Space Vite Plugin --------------------------------------------------------
// Convention-based route/middleware scanning
// Composes @spacefn/vite-plugin for code generation and Vite lifecycle

import { space as baseSpace } from "@spacefn/vite-plugin";
import type { Generator } from "@spacefn/vite-plugin";
import type { Plugin } from "vite";

import { scanRoutes, scanMiddlewares } from "./generator.js";
import type { SpacePluginOptions, ScannedRoute, ScannedMiddleware } from "./types.js";

// --- Code Generation ----------------------------------------------------------

function generateRoutesCode(routes: ScannedRoute[]): string {
	const lines: string[] = ["// Auto-generated by @spacefn/server", "// Do not edit manually", ""];

	for (let i = 0; i < routes.length; i++) {
		const r = routes[i];
		const rel = `../src/routes/${r.path}`;
		lines.push(`import * as Route_${i} from "${rel}";`);
	}

	lines.push("");
	lines.push("export const routes = [");
	for (let i = 0; i < routes.length; i++) {
		const r = routes[i];
		lines.push(`\t{`);
		lines.push(`\t\tpattern: "${r.pattern}",`);
		lines.push(`\t\tmethod: "${r.method}",`);
		lines.push(`\t\thandler: () => Promise.resolve(Route_${i}),`);
		lines.push(`\t},`);
	}
	lines.push("];");
	lines.push("");

	return lines.join("\n");
}

function generateMiddlewaresCode(middlewares: ScannedMiddleware[]): string {
	const lines: string[] = ["// Auto-generated by @spacefn/server", "// Do not edit manually", ""];

	for (let i = 0; i < middlewares.length; i++) {
		const mw = middlewares[i];
		const rel = `../src/middlewares/${mw.path}`;
		lines.push(`import * as Middleware_${i} from "${rel}";`);
	}

	lines.push("");
	lines.push("export const middlewares = [");
	for (let i = 0; i < middlewares.length; i++) {
		const mw = middlewares[i];
		lines.push(`\t{`);
		lines.push(`\t\tname: "${mw.name}",`);
		lines.push(`\t\thandler: Middleware_${i}.default,`);
		lines.push(`\t},`);
	}
	lines.push("];");
	lines.push("");

	return lines.join("\n");
}

// --- Plugin Factory -----------------------------------------------------------

export function space(options: SpacePluginOptions = {}): Plugin {
	const root = options.root ?? process.cwd();

	// Create route generator: watch src/routes/ → generate .space/routes.ts
	const routeGenerator: Generator = {
		watch: "src/routes/**/*.ts",
		output: ".space/routes.ts",
		async generate() {
			const routes = await scanRoutes(root);
			if (routes.length === 0) return "";
			return generateRoutesCode(routes);
		},
	};

	// Create middleware generator: watch src/middlewares/ → generate .space/middlewares.ts
	const middlewareGenerator: Generator = {
		watch: "src/middlewares/**/*.ts",
		output: ".space/middlewares.ts",
		async generate() {
			const middlewares = await scanMiddlewares(root);
			if (middlewares.length === 0) return "";
			return generateMiddlewaresCode(middlewares);
		},
	};

	// Delegate to @spacefn/vite-plugin for Vite lifecycle + file writing
	return baseSpace({
		root,
		generators: [routeGenerator, middlewareGenerator],
	});
}

export type { SpacePluginOptions, ScannedRoute, ScannedMiddleware } from "./types.js";
